GET http://localhost:8080/api/spot
Accept: application/json

###
GET http://localhost:8080/api/spots/type/3/listUse
Accept: application/json

###
GET https://ulide-party-api.herokuapp.com/api/spotEvaluations/us_id/1/sp_id/1
Accept: application/json

###
POST https://ulide-party-api.herokuapp.com/api/spotEvaluations
Content-Type: application/json

{
  "se_rate": "5",
  "se_comment": "Coentrada",
  "sp_id": "1",
  "us_id": "4"
}

###
DELETE https://ulide-party-api.herokuapp.com/api/spotEvaluations/6
Accept: application/json

###
POST http://localhost:80/api/item
Content-Type: application/json

{}

###
POST http://localhost:3000/api/favSpots
Content-Type: application/json

{
  "sp_id": 4,
  "us_id": 2

}

###




