POST http://localhost:3000/api/userMessagesGroups
Content-Type: application/json

{
  "um_gr_id": 1,
  "me_text": "boas",
  "us_id": 1
}

###
GET http://localhost:3000/api/userMessagesGroups/group/1
Accept: application/json

###
