GET http://localhost:8080/api/tags
Accept: application/json

###
PUT http://localhost:8080/api/spots/15
Content-Type: application/json

{
    "sp_name": "3 Em Cena",
    "sp_email": "teste06@mail.com"
}

###
